import { test, expect } from '@playwright/test'
test('desktop disclosure supports keyboard, Escape and outside dismissal', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'What We Do', exact: true })
  await trigger.focus()
  await trigger.press('Enter')
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('#mega-0')).toBeVisible()
  await trigger.press('ArrowDown')
  await expect(page.locator('#mega-0 a').first()).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.locator('#mega-0')).toHaveCount(0)
  await trigger.click()
  await page.mouse.click(10, 850)
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
})
test('mobile modal locks scroll, contains focus, reveals service categories and restores focus', async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'Open navigation' })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Site navigation' })
  await expect(dialog).toBeVisible()
  expect(await page.locator('body').evaluate((el) => el.style.overflow)).toBe('hidden')
  await dialog.getByRole('button', { name: 'What We Do' }).click()
  await dialog.getByText('Publishing & content', { exact: true }).click()
  await expect(dialog.getByRole('link', { name: 'Copyediting', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
  expect(await page.locator('body').evaluate((el) => el.style.overflow)).toBe('')
})
