export const legacyRedirects: Record<string, string> = {
  '/about-us': '/company',
  '/contact-us': '/get-a-quote',
  '/portfolio': '/work',
  '/blogs': '/resources',
  '/cover-page-design-services': '/services/cover-page-design',
  '/copyediting-services': '/services/copyediting',
  '/proofreading-services': '/services/proofreading',
  '/typesetting-services': '/services/typesetting',
  '/data-conversion-services': '/services/data-conversion',
  '/scielo-xml-markup-services': '/services/scielo-xml-markup',
  '/indexing-services': '/services/indexing',
  '/graphic-design-image-services': '/services/graphic-design-image-services',
  '/ebook-creation-services': '/services/ebook-creation',
  '/translation-services': '/services/translation',
  '/desktop-publishing-services': '/services/desktop-publishing',
  '/elearning-localization-services': '/services/elearning-localization',
  '/subtitling-services': '/services/subtitling',
  '/voiceover-services': '/services/voiceover',
  '/transcription-services': '/services/transcription',
  '/accessibility-services': '/services/accessibility',
}
